<?xml version="1.0" encoding="utf-8"?><Database Name="ecommerce_site" Class="DbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-6KE5GGAV;Initial Catalog=ecommerce_site;Integrated Security=True;Encrypt=False" SettingsObjectName="ProjectNS.Properties.Settings" SettingsPropertyName="ecommerce_siteConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.category" Member="Categories">
    <Type Name="Category">
      <Column Name="pk" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="category_earbuds_category" Member="EarbudsCategories" ThisKey="pk" OtherKey="category_pk" Type="EarbudsCategory" />
      <Association Name="category_tea_category" Member="TeaCategories" ThisKey="pk" OtherKey="category_pk" Type="TeaCategory" />
    </Type>
  </Table>
  <Table Name="dbo.earbuds" Member="Earbuds">
    <Type Name="Earbud">
      <Column Name="pk" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="for_sale" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="earbud_earbuds_category" Member="EarbudsCategories" ThisKey="pk" OtherKey="earbuds_pk" Type="EarbudsCategory" />
    </Type>
  </Table>
  <Table Name="dbo.earbuds_categories" Member="EarbudsCategories">
    <Type Name="EarbudsCategory">
      <Column Name="earbuds_pk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="category_pk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="category_earbuds_category" Member="Category" ThisKey="category_pk" OtherKey="pk" Type="Category" IsForeignKey="true" />
      <Association Name="earbud_earbuds_category" Member="Earbud" ThisKey="earbuds_pk" OtherKey="pk" Type="Earbud" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[order]" Member="Orders">
    <Type Name="Order">
      <Column Name="pk" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="order_purchase" Member="Purchases" ThisKey="pk" OtherKey="order_pk" Type="Purchase" />
      <Association Name="user_order" Member="User" ThisKey="user_id" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.purchase" Member="Purchases">
    <Type Name="Purchase">
      <Column Name="pk" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="order_pk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="item_pk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="table_of_item_pk" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="order_purchase" Member="Order" ThisKey="order_pk" OtherKey="pk" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tea" Member="Teas">
    <Type Name="Tea">
      <Column Name="pk" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="for_sale" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="tea_tea_category" Member="TeaCategories" ThisKey="pk" OtherKey="tea_pk" Type="TeaCategory" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="balance" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Association Name="user_order" Member="Orders" ThisKey="id" OtherKey="user_id" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.tea_categories" Member="TeaCategories">
    <Type Name="TeaCategory">
      <Column Name="tea_pk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="category_pk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="category_tea_category" Member="Category" ThisKey="category_pk" OtherKey="pk" Type="Category" IsForeignKey="true" />
      <Association Name="tea_tea_category" Member="Tea" ThisKey="tea_pk" OtherKey="pk" Type="Tea" IsForeignKey="true" />
    </Type>
  </Table>
</Database>